POST http://localhost:3001/api/cart/

Content-Type: application/json 
{
  "name": "Banana Nut Bread",
  "price": "$15.00",
  "photo": "https://images.unsplash.com/photo-1606101273945-e9eba91c0dc4?ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=1770&q=80",
  "quantity": 2
}